image: alpine:latest

deploy1:
  stage: deploy
  script:
    - apk update
    - apk add openssh
    - mkdir .ssh
    - ssh-keyscan $BOT_HOST > .ssh/known_hosts
    - echo $SSH_KEY_DEBOTS > .ssh/id_rsa
    - ssh -p $SSH_PORT $BOT_HOST $CMD_PATH