image: alpine:latest

deploy1:
  stage: deploy
  script:
    - apk update
    - apk add openssh
    - mkdir ~/.ssh
    - chmod 0700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT $BOT_HOST > ~/.ssh/known_hosts
    - echo "$SSH_KEY_DEBOTS" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - chmod 0700 ~/.ssh ~
    - ssh -p $SSH_PORT $BOT_USER@$BOT_HOST $CMD_PATH